/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.ThuPhiDongGop;

import controller.ThongKeController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoKhau;
import model.KhoanThu;
import model.NhanKhau;
import model.ThuPhiDongGop;
import service.HoKhauService;
import service.KhoanThuService;
import service.NhanKhauService;
import service.ThuPhiDongGopService;

/**
 *
 * @author phamd
 */
public class ThuPhiDongGopFR extends javax.swing.JFrame {

    /**
     * Creates new form ThuPhiDongGopFR
     */
    HoKhauService hoKhauService = new HoKhauService();
    NhanKhauService nhanKhauService = new NhanKhauService();
    KhoanThuService khoanThuService = new KhoanThuService();
    ThuPhiDongGopService tmp =  new ThuPhiDongGopService();
    public ThuPhiDongGopFR() {
        initComponents();
        
        ArrayList<KhoanThu> khoanthu;
        khoanthu = khoanThuService.dsCacKhoanThu();
        
        DotJcb.addItem("Tất cả");
        for (KhoanThu i : khoanthu){
            String s = i.getIDKhoanThu().substring(0,2);
            if ("dg".equals(s)) {
                DotJcb.addItem(i.getTenKhoanThu());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJpn = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        ShowButton = new javax.swing.JButton();
        DotJcb = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnChiTiet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textCount = new javax.swing.JLabel();
        txtTong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thu phí đóng góp");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableJpn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số hộ khẩu", "Tên chủ hộ", "Tên khoản thu", "Đã thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableJpn.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableJpn);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 510, 230));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Đợt:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        ShowButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ShowButton.setText("Tìm kiếm");
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ShowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 105, 30));

        DotJcb.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DotJcb.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                DotJcbComponentAdded(evt);
            }
        });
        jPanel1.add(DotJcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 330, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Số lượng :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        btnChiTiet.setText("Chi tiết");
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        jPanel1.add(btnChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tổng:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        textCount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textCount.setText("   ");
        jPanel1.add(textCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        txtTong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTong.setText("   ");
        jPanel1.add(txtTong, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
        String selectedDot = (String) DotJcb.getSelectedItem();
        
            
            DefaultTableModel df = (DefaultTableModel)tableJpn.getModel();
            df.setRowCount(0);
            tmp.dsDaThu();
            
            int tong = 0;
            int cnt = 0;
            
            List<HoKhau> danhSachHoKhau = new ArrayList<HoKhau>();
            danhSachHoKhau = hoKhauService.layDanhSachHoKhau();
            for(HoKhau i: danhSachHoKhau){
                String idkhoanthu = khoanThuService.getIDKhoanThu(selectedDot);
                if ("Tất cả".equals(selectedDot))
                    idkhoanthu = selectedDot;
//                ArrayList<Integer> list = khoanThuService.getSoTien1Ho(i.getSoHoKhau(), idkhoanthu );
                int sumSoLuong = khoanThuService.getSoTien1Ho(i.getSoHoKhau(), idkhoanthu );
                
                if (sumSoLuong > 0){
                    tong += sumSoLuong;
                    cnt ++;
                    df.addRow(new Object[]{i.getSoHoKhau(), i.getTenChuHo(), selectedDot, sumSoLuong});
                }
            }
            
            textCount.setText(String.valueOf(cnt));
            txtTong.setText(String.valueOf(tong));
    }//GEN-LAST:event_ShowButtonActionPerformed

    private void DotJcbComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_DotJcbComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_DotJcbComponentAdded

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df=(DefaultTableModel) tableJpn.getModel();
        int index=tableJpn.getSelectedRow();
        if (index < 0) {// lỗi chưa chọn đối tượng cần thao tác
            JOptionPane.showMessageDialog(this, "Chưa chọn đối tượng!");
            return;    
        }  
        
        String sohokhau = (String)df.getValueAt(index, 0);
        String tenchuho = (String)df.getValueAt(index, 1);
        new TPDGChiTiet(sohokhau, tenchuho).setVisible(true);
    }//GEN-LAST:event_btnChiTietActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuPhiDongGopFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuPhiDongGopFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuPhiDongGopFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuPhiDongGopFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThuPhiDongGopFR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DotJcb;
    private javax.swing.JButton ShowButton;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableJpn;
    private javax.swing.JLabel textCount;
    private javax.swing.JLabel txtTong;
    // End of variables declaration//GEN-END:variables
}
