/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.nhankhau;

import controller.TamVangManagerController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.NhanKhauService;

/**
 *
 * @author Vu
 */
public class BangTamVangFR extends javax.swing.JFrame {

    /**
     * Creates new form BangTamVangFR
     */
    
    TamVangManagerController tamVangControl = new TamVangManagerController();
    NhanKhauService nhanKhauService = new NhanKhauService();
    
    public BangTamVangFR() {
        initComponents();
        tamVangControl.capNhatBang(DSTamVangTable);
        ThongtinPanel.setVisible(false);
        xoabutton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DSTamVangTable = new javax.swing.JTable();
        capnhatbutton = new javax.swing.JButton();
        xoabutton = new javax.swing.JButton();
        huytrangthaibutton = new javax.swing.JButton();
        ThongtinPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelDenNgay = new javax.swing.JLabel();
        labelTuNgay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelNoiTamTru = new javax.swing.JLabel();
        labelLyDo = new javax.swing.JLabel();
        suabutton = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        comboboxTimKiem = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonTimKiem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bảng Tạm Vắng");

        DSTamVangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã giấy tạm vắng", "Số hộ khẩu", "Mã định danh", "Họ tên", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DSTamVangTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DSTamVangTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DSTamVangTable);

        capnhatbutton.setText("Cập nhật trạng thái");
        capnhatbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatbuttonActionPerformed(evt);
            }
        });

        xoabutton.setText("Xóa tạm vắng");
        xoabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoabuttonActionPerformed(evt);
            }
        });

        huytrangthaibutton.setText("Hủy trạng thái tạm vắng");
        huytrangthaibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huytrangthaibuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Lý do:");

        jLabel2.setText("Thời gian từ ngày:");

        jLabel3.setText("đến ngày");

        jLabel4.setText("Nơi tạm trú:");

        javax.swing.GroupLayout ThongtinPanelLayout = new javax.swing.GroupLayout(ThongtinPanel);
        ThongtinPanel.setLayout(ThongtinPanelLayout);
        ThongtinPanelLayout.setHorizontalGroup(
            ThongtinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongtinPanelLayout.createSequentialGroup()
                .addGroup(ThongtinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongtinPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNoiTamTru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ThongtinPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(ThongtinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThongtinPanelLayout.setVerticalGroup(
            ThongtinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongtinPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ThongtinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNoiTamTru, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThongtinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ThongtinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        suabutton.setText("Sửa tạm vắng");
        suabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suabuttonActionPerformed(evt);
            }
        });

        comboboxTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboboxTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Họ tên", "Mã định danh" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tìm kiếm theo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nhập thông tin tìm kiếm:");

        buttonTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonTimKiem.setText("Tìm kiếm");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tìm kiếm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(suabutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(capnhatbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(huytrangthaibutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xoabutton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel5)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboboxTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jScrollPane1)
                    .addComponent(ThongtinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(comboboxTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTimKiem))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ThongtinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suabutton)
                    .addComponent(capnhatbutton)
                    .addComponent(huytrangthaibutton)
                    .addComponent(xoabutton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void autoUpdate(){
        tamVangControl.capNhatBang(DSTamVangTable);
        labelNoiTamTru.setText("");
        labelTuNgay.setText("");
        labelDenNgay.setText("");
        labelLyDo.setText("");
        ThongtinPanel.setVisible(false);
    }
    
    private void DSTamVangTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DSTamVangTableMouseClicked
        // TODO add your handling code here:
        ThongtinPanel.setVisible(true);
        try{
            DefaultTableModel df=(DefaultTableModel) DSTamVangTable.getModel();
            int index=DSTamVangTable.getSelectedRow();
            String magiaytamvang = (String)df.getValueAt(index, 0);
            tamVangControl.hienThiChiTiet(magiaytamvang, labelNoiTamTru, labelTuNgay, labelDenNgay, labelLyDo);
            if(((String)df.getValueAt(index, 0)).equals("Hoàn thành tạm vắng")){
                huytrangthaibutton.setEnabled(false);
            }
        }catch(Exception ex){
        }
    }//GEN-LAST:event_DSTamVangTableMouseClicked

    private void capnhatbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatbuttonActionPerformed
        // TODO add your handling code here:
        autoUpdate();
    }//GEN-LAST:event_capnhatbuttonActionPerformed

    private void xoabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoabuttonActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel df=(DefaultTableModel) DSTamVangTable.getModel();
            int index=DSTamVangTable.getSelectedRow();
            if (index < 0) // lỗi chưa chọn đối tượng cần thao tác
            {
                JOptionPane.showMessageDialog(this, "Chưa chọn đối tượng!");
                return;
            }
            String magiaytamvang = (String)df.getValueAt(index,0) ;
            int fl = tamVangControl.xoaTamVang(magiaytamvang);
            if (fl == 1) // xóa thành công
            {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                autoUpdate();
                return;
            }
            else {
                JOptionPane.showMessageDialog(this, "Xóa không thành công!");
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_xoabuttonActionPerformed

    private void huytrangthaibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huytrangthaibuttonActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel df=(DefaultTableModel) DSTamVangTable.getModel();
            int index=DSTamVangTable.getSelectedRow();
            if (index < 0) // lỗi chưa chọn đối tượng cần thao tác
            {
                JOptionPane.showMessageDialog(this, "Chưa chọn đối tượng!");
                return;
            }
            String sohokhau = (String)df.getValueAt(index, 1);
            String madinhdanh = (String)df.getValueAt(index, 2);
            String magiaytamvang = (String)df.getValueAt(index, 0);
            
            int i = tamVangControl.capNhatTinhTrangTamVang("Hoàn thành tạm vắng",magiaytamvang);
            System.out.print(i);
            if(i==1){
                nhanKhauService.capNhatTrangThai("Thường trú",sohokhau, madinhdanh);
                JOptionPane.showMessageDialog(this, "Cập nhật tình trạng thành công !");
            }else{
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại !");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_huytrangthaibuttonActionPerformed

    private void suabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suabuttonActionPerformed
        // TODO add your handling code here:
        //Chỉ sứa những thằng tạm vắng
        try{
            DefaultTableModel df=(DefaultTableModel) DSTamVangTable.getModel();
            int index=DSTamVangTable.getSelectedRow();
            if (index < 0) // lỗi chưa chọn đối tượng cần thao tác
            {
                JOptionPane.showMessageDialog(this, "Chưa chọn đối tượng!");
                return;
            }
            
            String maGiayTamVang = (String)df.getValueAt(index, 0);
            tamVangControl.setMaGiayTamVang(maGiayTamVang);
            new SuaTamVangFR().setVisible(true);
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_suabuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BangTamVangFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BangTamVangFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BangTamVangFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BangTamVangFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BangTamVangFR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DSTamVangTable;
    private javax.swing.JPanel ThongtinPanel;
    private javax.swing.JButton buttonTimKiem;
    private javax.swing.JButton capnhatbutton;
    private javax.swing.JComboBox<String> comboboxTimKiem;
    private javax.swing.JButton huytrangthaibutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDenNgay;
    private javax.swing.JLabel labelLyDo;
    private javax.swing.JLabel labelNoiTamTru;
    private javax.swing.JLabel labelTuNgay;
    private javax.swing.JButton suabutton;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JButton xoabutton;
    // End of variables declaration//GEN-END:variables
}
