/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.nhankhau;

import controller.NhanKhauManagerController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.hokhau.ThemNhanKhauFR;

/**
 *
 * @author phamd
 */
public class NhanKhauFR extends javax.swing.JFrame {

    /**
     * Creates new form NhanKhauFR
     */
    NhanKhauManagerController nhanKhauControl = new NhanKhauManagerController();
    public NhanKhauFR() {
        initComponents();
        autoUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chitietbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DSNhanKhauTable = new javax.swing.JTable();
        captamtrubutton = new javax.swing.JButton();
        capnhatbutton = new javax.swing.JButton();
        dstamtrubutton = new javax.swing.JButton();
        dstamvangbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        comboboxTimKiem = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhân khẩu");

        chitietbutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chitietbutton.setText("Xem chi tiết");
        chitietbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chitietbuttonActionPerformed(evt);
            }
        });

        DSNhanKhauTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã định danh", "Số hộ khẩu", "Họ tên", "Ngày sinh", "Giới tính", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DSNhanKhauTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DSNhanKhauTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DSNhanKhauTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DSNhanKhauTable);

        captamtrubutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        captamtrubutton.setText("Cấp giấy tạm trú");
        captamtrubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captamtrubuttonActionPerformed(evt);
            }
        });

        capnhatbutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        capnhatbutton.setText("Cập nhật trạng thái");
        capnhatbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatbuttonActionPerformed(evt);
            }
        });

        dstamtrubutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dstamtrubutton.setText("Danh sách tạm trú");
        dstamtrubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dstamtrubuttonActionPerformed(evt);
            }
        });

        dstamvangbutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dstamvangbutton.setText("Danh sách tạm vắng");
        dstamvangbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dstamvangbuttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Tìm kiếm:");

        comboboxTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboboxTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Họ tên", "Mã định danh", "Số hộ khẩu" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tìm kiếm theo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nhập thông tin tìm kiếm:");

        buttonTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonTimKiem.setText("Tìm kiếm");
        buttonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(comboboxTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(capnhatbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dstamvangbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(dstamtrubutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(captamtrubutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chitietbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(comboboxTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTimKiem))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chitietbutton)
                        .addGap(12, 12, 12)
                        .addComponent(captamtrubutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dstamtrubutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dstamvangbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(capnhatbutton)
                        .addGap(0, 168, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void autoUpdate() {
        nhanKhauControl.capNhatBang(DSNhanKhauTable);
    }
    private void chitietbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chitietbuttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df=(DefaultTableModel) DSNhanKhauTable.getModel();
        int index=DSNhanKhauTable.getSelectedRow();
        if (index < 0) {// lỗi chưa chọn đối tượng cần thao tác
            JOptionPane.showMessageDialog(this, "Chưa chọn đối tượng!");
            return;    
        }  
        nhanKhauControl.setMaDinhDanh((String)df.getValueAt(index, 0));
        nhanKhauControl.setSoHoKhau((String)df.getValueAt(index, 1));
        new ChiTietNhanKhauFR().setVisible(true);
        
    }//GEN-LAST:event_chitietbuttonActionPerformed

    private void DSNhanKhauTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DSNhanKhauTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DSNhanKhauTableMouseClicked

    private void captamtrubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captamtrubuttonActionPerformed
        // TODO add your handling code here:
//        DefaultTableModel df=(DefaultTableModel) DSNhanKhauTable.getModel();
//        int index=DSNhanKhauTable.getSelectedRow();
//        if (index < 0) {// lỗi chưa chọn đối tượng cần thao tác
//            JOptionPane.showMessageDialog(this, "Chưa chọn đối tượng!");
//            return;    
//        }  
//        nhanKhauControl.setMaDinhDanh((String)df.getValueAt(index, 0));
//        nhanKhauControl.setSoHoKhau((String)df.getValueAt(index, 1));
        new ThemTamTruFR().setVisible(true);
    }//GEN-LAST:event_captamtrubuttonActionPerformed

    private void capnhatbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatbuttonActionPerformed
        // TODO add your handling code here:
        autoUpdate();
    }//GEN-LAST:event_capnhatbuttonActionPerformed

    private void dstamtrubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dstamtrubuttonActionPerformed
        // TODO add your handling code here:
        new BangTamTruFR().setVisible(true);
    }//GEN-LAST:event_dstamtrubuttonActionPerformed

    private void dstamvangbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dstamvangbuttonActionPerformed
        // TODO add your handling code here:
        new BangTamVangFR().setVisible(true);
    }//GEN-LAST:event_dstamvangbuttonActionPerformed

    private void buttonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTimKiemActionPerformed
        // TODO add your handling code here:
        nhanKhauControl.timKiemNhankhau(comboboxTimKiem, DSNhanKhauTable, txtTimKiem.getText());
    }//GEN-LAST:event_buttonTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanKhauFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanKhauFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanKhauFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanKhauFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanKhauFR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DSNhanKhauTable;
    private javax.swing.JButton buttonTimKiem;
    private javax.swing.JButton capnhatbutton;
    private javax.swing.JButton captamtrubutton;
    private javax.swing.JButton chitietbutton;
    private javax.swing.JComboBox<String> comboboxTimKiem;
    private javax.swing.JButton dstamtrubutton;
    private javax.swing.JButton dstamvangbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
